language: ruby
rbenv:
- 2.7.2
script:
  - sudo gem install bundler -v 2.2.30
addons:
  postgresql: 9.6
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider:
  api_key:
    secure:
  app:
  run:
  on:
    branch: main
