language: ruby
rbenv:
- 2.7.2
addons:
  postgresql: 9.6
script:
- bundle update --bundler
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider:
  api_key:
    secure:
  app:
  run:
  on:
    branch: main
