# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@0.1.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
    executor: ruby-postgres
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: sudo gem install bundler -v 2.2.30
      - ruby/bundle-install
      - resolve-dependencies
      - run-linter
      - setup-postgres
      - run-tests-rails
