version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          PGHOST: localhost
          PGUSER: bonez-be
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: bonez-be
          POSTGRES_DB: bonez-be_test
          POSTGRES_PASSWORD: ""
    steps:
      - checkout

      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: your-app-name-{{ checksum "Gemfile.lock" }}

      # Bundle install dependencies
      - run: sudo gem install bundler -v 2.2.30
      - run: bundle install --path vendor/bundle

      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: bonez-be-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle

      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rspec
